name: PR

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: cache vendor folder
        uses: actions/cache@v4
        with:
          path: ./vendor
          key: ${{ github.sha }}

      - name: build app
        run: make start

      - name: validate pull request
        run: |
          make php args=".github/ci/pr '${{ github.event.pull_request.title }}'"
